#Application URL
url_old = https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
url = http://localhost/orangehrm/orangehrm-5.8.1/web/index.php/dashboard/index
#Browser Configuration
browser = chrome

#Credentials
username = orangehrm_hverma
password = Morechips@1997

#ImplicitWait ( in seconds)
implicitwait = 10